# Results

## Build the Model

Prior to building the statistical model the baseline factor was set to ‘general surgery’ instead of the default ‘cardiac surgery’ to determine the impact, if any, on the linear regression model with regards to the null hypothesis.

A bivariate multiple linear regression model was constructed with two dependent variables (consult_90th and surgery_90th), representing the 90th percentiles for each instance of a surgical specialty’s wait time, added together to give the combined surgical wait time and one independent variable.

#### A summary of the multiple linear regression model is as follows:

Call: lm(formula = specialty90 ~ specialty)

Residuals:  

Min     | 1Q      | Median    | 3Q    | Max
------- | ------- | --------- | ----- | ---------
-536.39 | -144.57 | -66.16    | 70.76 | 2366.55 


Coefficients:                   | Estimate Std.| Error | t value | Pr(>|t|)
------------------------------- | ------------ | ----- | ------- | ------------
(Intercept)                     | 257.71       | 38.80 | 6.643   | 1.68e-10 ***
specialtycardiac                | -117.31      | 135.51| -0.866  | 0.387417    
specialtydental                 | 180.16       | 82.30 | 2.189   | 0.029447 *  
specialtyneurosurgery           | 50.39        | 99.67 | 0.506   | 0.613607    
specialtyobstetrics/gynaecology | -24.23       | 59.68 | -0.406  | 0.685083    
specialtyophthalmology          | 250.74       | 63.71 | 3.935   | 0.000106 ***
specialtyoral maxillofacial     | 136.10       | 95.75 | 1.421   | 0.156338    
specialtyorthopaedic            | 440.68       | 61.02 | 7.222   | 5.19e-12 ***
specialtyotolaryngology (ent)   | 218.69       | 69.83 | 3.131   | 0.001930 ** 
specialtyplastic                | 115.49       | 84.41 | 1.368   | 0.172388    
specialtythoracic               | -39.88       | 124.72| -0.320  | 0.749385    
specialtyurology                | 15.10        | 73.05 | 0.207   | 0.836358    
specialtyvascular               | 100.79       | 124.72| 0.808   | 0.419727    
  
Signif. codes:  0 | *** 0.001 | ** 0.01 | * 0.05 | '.' 0.1 | ' ' 1

Residual standard error: 290.3 on 271 degrees of freedom  
Multiple R-squared:  0.2383,    Adjusted R-squared:  0.2046   
F-statistic: 7.066 on 12 and 271 DF,  p-value: 3.522e-11

#### From the above summary of the model, the following statistical measures were extracted:

degrees of freedom: 13 and 271

p-value of the model: 3.522271910^{-11}

residual standard error: 290.3315348

F-statistic: 7.0658736

F-critical: 1.7583858  

#### An analysis of variance (ANOVA) of the linear regression model was used to validate the model:  

Analysis of Variance Table

Response: specialty90  
  
Measure   | Df   | Sum Sq  | Mean Sq | F value  | Pr(>F)
--------- | ---- | ------- | ------- | -------- | -------------
specialty | 12   | 7147193 | 595599  | 7.0659   | 3.522e-11 ***
Residuals | 271  | 22843240| 84292   |          | 
